// Generated by gencpp from file addtwoints_pack/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ADDTWOINTS_PACK_MESSAGE_ADDTWOINTS_H
#define ADDTWOINTS_PACK_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <addtwoints_pack/AddTwoIntsRequest.h>
#include <addtwoints_pack/AddTwoIntsResponse.h>


namespace addtwoints_pack
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace addtwoints_pack


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::addtwoints_pack::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::addtwoints_pack::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::addtwoints_pack::AddTwoInts > {
  static const char* value()
  {
    return "addtwoints_pack/AddTwoInts";
  }

  static const char* value(const ::addtwoints_pack::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::addtwoints_pack::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::addtwoints_pack::AddTwoInts > 
template<>
struct MD5Sum< ::addtwoints_pack::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::addtwoints_pack::AddTwoInts >::value();
  }
  static const char* value(const ::addtwoints_pack::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::addtwoints_pack::AddTwoIntsRequest> should match 
// service_traits::DataType< ::addtwoints_pack::AddTwoInts > 
template<>
struct DataType< ::addtwoints_pack::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::addtwoints_pack::AddTwoInts >::value();
  }
  static const char* value(const ::addtwoints_pack::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::addtwoints_pack::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::addtwoints_pack::AddTwoInts > 
template<>
struct MD5Sum< ::addtwoints_pack::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::addtwoints_pack::AddTwoInts >::value();
  }
  static const char* value(const ::addtwoints_pack::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::addtwoints_pack::AddTwoIntsResponse> should match 
// service_traits::DataType< ::addtwoints_pack::AddTwoInts > 
template<>
struct DataType< ::addtwoints_pack::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::addtwoints_pack::AddTwoInts >::value();
  }
  static const char* value(const ::addtwoints_pack::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ADDTWOINTS_PACK_MESSAGE_ADDTWOINTS_H
